export const FETCH_RESPONSE = "FETCH_RESPONSE";
export const SEARCH_RESPONSE = "SEARCH_RESPONSE";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const SET_LOADING = "SET_LOADING";
export const SET_PAGE_TOKEN = "SET_PAGE_TOKEN";
